language: java
sudo: false
services:
- mongodb
- docker
script: mvn clean clover:setup verify clover:aggregate clover:clover
after_success:
- bash <(curl -s https://codecov.io/bash)
#- if [ "$TRAVIS_BRANCH" == "master" ]; then
#    mvn -Dmaven.test.skip=true clean package spring-boot:repackage docker:build;
#    docker tag develog ${HEROKU_REGISTRY_URL}/develog/web;
#    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_PASSWORD" $HEROKU_REGISTRY_URL;
#    docker push ${HEROKU_REGISTRY_URL}/develog/web;
#    fi
deploy:
  provider: heroku
  app: develog
  api_key:
    secure: Vk/tAz860lOzZXSjir9EidpIv+ka2cAZZMdxpHnbC448c5H7Kfqdii4yFtYsLFPMXchwR/hM83M3+UPaj4blErvx9wFFHYjQ8/8WWX2mamOlBghTlI/XFmxtnMHoZTpMZMOhOcWT7oWw1GvGxXxzp31rqRZSwThu8teqTbJImkzGKlrk7GGeh2OR3KvDyAnJPCIk56tDc3O/uivsPivGukvOvZEeKLm5xePEuVUuYbZ8nH7D6dY322xaskhkOLQtnG88bllWqrp46XuG73GPz5XGtWZoyz9daitv+96ISrRRBjDPGQUNBuW0loCQtilttIzw96vaD1xhu7cjoi8xWB1jNSh1MTUWXooRgW/bKLYvzSvoVDYLymTnkS0RqKxkBvXyHIAYlWwvgscg4MROnRvcEYkiiacz0+TtHdrHcLCmwZHlPLa+vXwHSd8kwHEpgv+LKJahlv+DuiJpMNHtxjgyGVEYfvfSOFGV/E+YXcKcuFQ0nf52kbykRpN7L0QcGPFICfNGxDOPkzPPLD8/YolVKmiOTlCp+3s8Zs97xpj7OpGT5HsVqk1Q1KT0IPgiCRshkRDQG2tQnwYFlT8jzWr6xd86bl1bTDncgcEHqY7oOrnCmQQdEtrOJQ970r1vaudy2B0jD6bIQcEqopx90wQYTmlsa/phyws9so7w+r8=
  on:
    repo: T3r1jj/Develog
    branch: master
